en-us/app/Http/routes.php
Route::post('search',['as'=>'search','uses'=>'SearchController@search'] );
Route::post('search-service',['as'=>'search.service','uses'=>'SearchController@searchService'] );

/**
 * API Routes
 */

Route::group(['prefix' => 'find-a-doctor'], function() {
    Route::get('/',['as'=>'physician.index','uses'=>'PhysicianController@index']);
    Route::get('/{doctor_slug}',['as'=>'physician.single','uses'=>'PhysicianController@single']);
});


Route::group(['prefix' => 'clinical-services'], function() {
    Route::get('/', ['as' => 'department.index', 'uses' => 'DepartmentController@index']);
    Route::get('/{department_slug}', ['as' => 'department.single', 'uses' => 'DepartmentController@single']);
});


Route::group(['prefix' => 'patients'], function() {
    Route::get('/', function () { return view('pages.patients.services'); });
    Route::get('/our-services', function () { return view('pages.patients.services'); });
    Route::get('/insurance', function () { return view('pages.patients.insurance'); });
    Route::get('/at-healthpoint', function () { return view('pages.patients.at-healthpoint'); });

    Route::group(['prefix' => 'newsletters'], function() {
        Route::get('/',['as'=>'media.patient-newsletters','uses'=>'MediaController@newsletters']);
        Route::get('/{slug}',['as'=>'media.patient-newsletters.single','uses'=>'MediaController@singleNewsletter']);
    });

});


Route::group(['prefix' => 'health-tips'], function() {
    Route::get('/',['as'=>'blog.index','uses'=>'BlogController@index']);
    Route::get('/{article_id}',['as'=>'blog.single','uses'=>'BlogController@single']);
});

Route::get('page/{slug}',['as'=>'pages.single','uses'=>'PageController@article']);

Route::group(['prefix' => 'work-with-us'], function() {

    Route::get('/', function () { return view('pages.work-with-us.working-for-healthpoint'); });
    Route::get('/emiratization', function () { return view('pages.work-with-us.emiratization'); });
    Route::get('/careers', function () { return view('pages.work-with-us.opportunities'); });
});


Route::group(['prefix' => 'media'], function() {

    Route::get('/news',['as'=>'media.news','uses'=>'MediaController@news']);
    Route::get('/news/{slug}',['as'=>'media.news.single','uses'=>'MediaController@single']);

    Route::get('/hospital-campaigns',['as'=>'media.campaigns','uses'=>'MediaController@campaigns']);
    Route::get('/hospital-campaigns/{slug}',['as'=>'media.campaigns.single','uses'=>'MediaController@single']);

    Route::get('/seminars-and-workshops',['as'=>'media.seminars','uses'=>'MediaController@seminars']);
    Route::get('/seminars-and-workshops/{slug}',['as'=>'media.seminars.single','uses'=>'MediaController@singleEvent']);

    Route::group(['prefix' => 'galleries'], function() {
        Route::get('/', ['as' => 'pages.media.album', 'uses' => 'MediaController@galleries']);
        Route::get('/{slug}', ['as' => 'pages.media.album.single', 'uses' => 'MediaController@album']);
    });
});

Route::group(['prefix' => 'events'], function() {
    Route::get('/',['as'=>'events.index','uses'=>'EventController@index']);
    Route::get('/upcoming',['as'=>'events.upcoming','uses'=>'EventController@index']);
    Route::get('/past',['as'=>'events.past','uses'=>'EventController@past']);
    Route::get('/{slug}',['as'=>'events.single','uses'=>'EventController@show']);
});

Route::group(['prefix' => 'surveys'], function() {
    Route::get('/',['as'=>'surveys.index','uses'=>'SurveyController@index']);
    Route::get('/{slug}',['as'=>'surveys.single','uses'=>'SurveyController@show']);
    Route::post('/store',['as'=>'surveys.store','uses'=>'SurveyController@store']);
});

Route::get('/page/{slug}',['as'=>'page.single','uses'=>'MediaController@singlePage']);

Route::group(['prefix' => 'cp'], function() {

    Route::get('/',function(){ return redirect()->route('admin.login'); });
    Route::post('/login-post',['as'=>'admin.login.validate','uses'=>'Auth\AuthController@login']);
    Route::get('/login',['as'=>'admin.login','uses'=>'AdminController@login','middleware' => 'guest']);
    Route::get('/logout',['as'=>'admin.logout','uses'=>'Auth\AuthController@logout']);

    Route::group(['prefix' => 'articles','middleware' => 'auth'], function() {
        Route::get('/',                     ['as'=>'admin.articles.index','uses'=>'AdminController@articles']);
        Route::get('/create',               ['as'=>'admin.articles.create','uses'=>'Admin\ArticleController@create']);
        Route::post('/store',               ['as'=>'admin.articles.store','uses'=>'Admin\ArticleController@store']);
        Route::get('/edit/{id}',            ['as'=>'admin.articles.edit','uses'=>'Admin\ArticleController@edit']);
        Route::post('/update',              ['as'=>'admin.articles.update','uses'=>'Admin\ArticleController@update']);
        Route::get('/delete/{id}',          ['as'=>'admin.articles.delete','uses'=>'Admin\ArticleController@delete']);
        Route::get('/category/{category}',  ['as'=>'admin.articles.get','uses'=>'Admin\ArticleController@index']);
    });

    Route::group(['prefix' => 'physicians','middleware' => 'auth'], function() {
        Route::get('/',                     ['as'=>'admin.physicians.index','uses'=>'AdminController@physicians']);
        Route::get('/create',               ['as'=>'admin.physicians.create','uses'=>'Admin\PhysicianController@create']);
        Route::post('/store',               ['as'=>'admin.physicians.store','uses'=>'Admin\PhysicianController@store']);
        Route::get('/edit/{id}',            ['as'=>'admin.physicians.edit','uses'=>'Admin\PhysicianController@edit']);
        Route::post('/update',              ['as'=>'admin.physicians.update','uses'=>'Admin\PhysicianController@update']);
        Route::get('/delete/{id}',          ['as'=>'admin.physicians.delete','uses'=>'Admin\PhysicianController@delete']);
        Route::get('/feature/{id}',          ['as'=>'admin.physicians.feature','uses'=>'Admin\PhysicianController@feature']);
        Route::get('/unfeature/{id}',          ['as'=>'admin.physicians.unfeature','uses'=>'Admin\PhysicianController@unfeature']);
    });

    Route::group(['prefix' => 'departments','middleware' => 'auth'], function() {
        Route::get('/',                     ['as'=>'admin.departments.index','uses'=>'AdminController@departments']);
        Route::get('/create',               ['as'=>'admin.departments.create','uses'=>'Admin\DepartmentController@create']);
        Route::post('/store',               ['as'=>'admin.departments.store','uses'=>'Admin\DepartmentController@store']);
        Route::get('/edit/{id}',            ['as'=>'admin.departments.edit','uses'=>'Admin\DepartmentController@edit']);
        Route::post('/update',              ['as'=>'admin.departments.update','uses'=>'Admin\DepartmentController@update']);
        Route::get('/delete/{id}',          ['as'=>'admin.departments.delete','uses'=>'Admin\DepartmentController@delete']);
    });

    Route::group(['prefix' => 'insurances','middleware' => 'auth'], function() {
        Route::get('/',                     ['as'=>'admin.insurances.index','uses'=>'AdminController@insurances']);
        Route::get('/create',               ['as'=>'admin.insurances.create','uses'=>'Admin\InsuranceController@create']);
        Route::post('/store',               ['as'=>'admin.insurances.store','uses'=>'Admin\InsuranceController@store']);
        Route::get('/edit/{id}',            ['as'=>'admin.insurances.edit','uses'=>'Admin\InsuranceController@edit']);
        Route::post('/update',              ['as'=>'admin.insurances.update','uses'=>'Admin\InsuranceController@update']);
        Route::get('/delete/{id}',          ['as'=>'admin.insurances.delete','uses'=>'Admin\InsuranceController@delete']);
    });

    Route::group(['prefix' => 'careers','middleware' => 'auth'], function() {
        Route::get('/',                     ['as'=>'admin.careers.index','uses'=>'AdminController@careers']);
        Route::get('/create',               ['as'=>'admin.careers.create','uses'=>'Admin\CareerController@create']);
        Route::post('/store',               ['as'=>'admin.careers.store','uses'=>'Admin\CareerController@store']);
        Route::get('/edit/{id}',            ['as'=>'admin.careers.edit','uses'=>'Admin\CareerController@edit']);
        Route::post('/update',              ['as'=>'admin.careers.update','uses'=>'Admin\CareerController@update']);
        Route::get('/delete/{id}',          ['as'=>'admin.careers.delete','uses'=>'Admin\CareerController@delete']);
    });

    Route::group(['prefix' => 'tweets','middleware' => 'auth'], function() {
        Route::get('/',                     ['as'=>'admin.tweets.index','uses'=>'AdminController@tweets']);
        Route::get('/create',               ['as'=>'admin.tweets.create','uses'=>'Admin\TweetController@create']);
        Route::post('/store',               ['as'=>'admin.tweets.store','uses'=>'Admin\TweetController@store']);
        Route::get('/edit/{id}',            ['as'=>'admin.tweets.edit','uses'=>'Admin\TweetController@edit']);
        Route::post('/update',              ['as'=>'admin.tweets.update','uses'=>'Admin\TweetController@update']);
        Route::get('/delete/{id}',          ['as'=>'admin.tweets.delete','uses'=>'Admin\TweetController@delete']);
    });

    Route::group(['prefix' => 'galleries','middleware' => 'auth'], function() {
        Route::get('/',                     ['as'=>'admin.galleries.index','uses'=>'AdminController@galleries']);
        Route::get('/create',               ['as'=>'admin.galleries.create','uses'=>'Admin\GalleryController@create']);
        Route::post('/store',               ['as'=>'admin.galleries.store','uses'=>'Admin\GalleryController@store']);
        Route::get('/edit/{id}',            ['as'=>'admin.galleries.edit','uses'=>'Admin\GalleryController@edit']);

en-us/app/Models/Survey/Survey.php
<?php

namespace App\Models\Survey;

use Illuminate\Database\Eloquent\Model;

class Survey extends Model
{
    protected $fillable = ['title','slug','description'];

    public $dates = ['date_start','date_end'];

    public function questions(){
        return $this->hasMany('App\Models\Survey\SurveyQuestion');
    }

    public function entries(){
        return $this->hasMany('App\Models\Survey\SurveyQuestionAnswer');
    }

    /**
     * A Survey has uploads.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function uploads()
    {
        return $this->morphOne('App\Models\Upload', 'uploadable');
    }


    /**
     * get Thumbnail Attrib
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function getThumbnailSquareAttribute()
    {
        $thumb = $this->uploads()->where('template', 'square')->first();

        return $thumb ? asset('public'.$thumb->url ) : 'http://placehold.it/240x240';
    }


    /**
     * get Thumbnail Attrib
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function getPhotoAttribute()
    {
        $thumb = $this->uploads()->where('template', 'photo')->first();

        return $thumb ? asset('public'.$thumb->url ) : null;
    }

    /**
     * get Thumbnail Attrib
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function getThumbnailLongAttribute()
    {
        $thumb = $this->uploads()->where('template', 'long')->first();

        return $thumb ? asset('public'.$thumb->url ) : null;
    }

    /**
     * get Thumbnail Attrib
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function getThumbnailAttribute()
    {
        $thumb = $this->uploads()->where('template', 'thumb')->first();
        return $thumb ? asset('public'.$thumb->url ) : 'http://placehold.it/320x240';
    }

    /**
     * get Thumbnail Attrib
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function getThumbnailOriginalAttribute()
    {
        $thumb = $this->uploads()->where('template', 'original')->first();
        return $thumb ? asset('public'.$thumb->url ) : 'http://placehold.it/320x240';
    }

    /**
     * get Thumbnail Attrib
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function getThumbnailHighAttribute()
    {
        $thumb = $this->uploads()->where('template', 'high')->first();
        return $thumb ? asset('public'.$thumb->url ) : 'http://placehold.it/320x240';
    }


}

en-us/app/Models/Survey/SurveyQuestion.php
<?php

namespace App\Models\Survey;

use Illuminate\Database\Eloquent\Model;

class SurveyQuestion extends Model
{
    protected $fillable = ['survey_id','survey_question_type_id','question','order','is_required','is_float'];

    public function type(){
        return $this->hasOne('App\Models\Survey\SurveyQuestionType','id','survey_question_type_id');
    }

    public function survey(){
        return $this->hasOne('App\Models\Survey\Survey','id','survey_id');
    }

    public function getTypeAttribute(){
        return $this->type()->first();
    }

    public function choices(){
        return $this->hasMany('App\Models\Survey\SurveyQuestionChoice');
    }

    public function getChoicesAttribute(){
        return $this->choices()->get();
    }

    public function getEntriesAttribute(){
        return $this->entries()->get();
    }
}

en-us/app/Models/Survey/SurveyQuestionAnswer.php
<?php

namespace App\Models\Survey;

use Illuminate\Database\Eloquent\Model;

class SurveyQuestionAnswer extends Model
{
    protected $fillable = ['survey_id','user_ip'];

    public function survey(){
        return $this->hasOne('App\Models\Survey\Survey','id','survey_id');
    }

    public function data(){
        return $this->hasMany('App\Models\Survey\SurveyQuestionAnswerItem');
    }

    public function getSurveyAttribute(){
        return $this->survey()->first();
    }
}

en-us/app/Http/Controllers/SurveyController.php
<?php

namespace App\Http\Controllers;

use App\Models\Option;
use App\Models\Survey\Survey;
use App\Models\Survey\SurveyQuestion;
use App\Models\Survey\SurveyQuestionAnswerItem;
use App\Models\Survey\SurveyQuestionChoiceRating;
use App\Models\Survey\SurveyQuestionType;
use Illuminate\Http\Request;

use App\Http\Requests;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Session;

class SurveyController extends Controller
{

    public $eto;

    public function __construct(Survey $model)
    {
        $this->model = $model;
    }

    public function index(){

        $data = [];
        $results = [];

//        print_r($this->convert([[1,2,[3,4],5],6,[7,8,9],10,[11,[12,[13,14,[15,16,17]]]]]));

        $data = $this->model->where('is_active',1)->orderBy('created_at','DESC')->paginate(8);
        return view('pages.surveys.index',compact('data'));
    }

    public function show($slug){
        $data = $this->model->where('slug',$slug)->first();

        if($data){

            if(!$data->is_active)
                return redirect()->route('surveys.index');

            $data->load('questions.type','questions.choices');

            return view('pages.surveys.show',compact('data'));
        }
    }

    public function store(Request $request){
        $survey = $this->model->find($request->input('id'));

        if($survey){
            $answers = $request->input('questions');

            $entry = $survey->entries()->create(['user_ip'=>$request->ip()]);

            foreach ($answers as $qID=>$answer){
                $question = SurveyQuestion::find($qID);

                if($question){
                    if($entry){

                        if(is_array($answer)){

                            if(isset($answer['choices'])){
                                foreach ($answer['choices'] as $rating){
                                    SurveyQuestionChoiceRating::create([
                                        'survey_question_choice_id'=>$rating['choice_id'],
                                        'survey_question_answer_id'=>$entry->id,
                                        'value'=>$rating['rate'],
                                    ]);
                                }
                            } else {
                                foreach ($answer as $item)
                                    $entry->data()->create(['value'=>$item,'survey_question_id'=>$question->id]);
                            }
                        }
                        else
                            $entry->data()->create(['value'=>$answer,'survey_question_id'=>$question->id]);
                    }
                }
            }


            $questions = SurveyQuestion::where('survey_id',$entry->survey->id)->get();
            $survey = Survey::find($entry->survey->id);

            if($questions && $survey){
                $data = [];
                $data['survey'] = $survey->title;

                foreach($questions as $index=>$question){
                    $data['questions'][$index]['question'] = $question->question;
                    $data['questions'][$index]['data'] = SurveyQuestionAnswerItem::where('survey_question_answer_id',$entry->id)->where('survey_question_id',$question->id)->get();
                }
            }


            $survey_emails = Option::where('slug','survey-emails')->pluck('value');

            foreach($survey_emails as $email){
                Mail::queue('emails.surveys.new', ['data' => $data], function ($m) use ($email) {
                    $m->from('surveys@healthpoint.ae', 'Healthpoint Survey');

                    $m->to($email, 'Healthpoint Survey Manager')->subject('Healthpoint Survey Entry');
                });
            }
        }

        Session::flash('success','Your entry has been submitted successfully. Thank you for your cooperation.');

        return redirect()->back();
    }


}

en-us/resources/views/admin/surveys/show.blade.php
@extends('admin.master')
<style>
    #surveyElements {
        position: relative;
        float: left;
        width: 100%;
    }
    #surveyElements .form-group {
        border: 3px solid #3694f7;
        padding: 5px 20px;
        width: 100%;
        background-color: #fff;
        position: relative;
        float: left;
    }
    #surveyElements .count, #surveyElements .delete-question, #surveyElements .move-question {
        border: 0;
        width: auto;
        background-color: #3694f7;
        width: 30px;
        height: 30px;
        text-align: center;
        padding-left: 5px;
        color: #fff;
        position: absolute;
        top: -3px;
        left: -32px;
        border-top-left-radius: 50%;
        border-bottom-left-radius: 50%;
        font-size: 16px;
    }

    #surveyElements .glyphicon {
        line-height: 30px;
        cursor: pointer;
    }

    #surveyElements .delete-question {
        top: 32px;
        left: -32px;
    }

    #surveyElements .form-group .delete-choice {
        margin-left: 5px;
        color: #fb4c4c;
    }

    #surveyElements .move-question {
        top: 67px;
        left: -32px;
    }

    .field-group input {
        margin-bottom: 5px;
        padding: 0px 10px;
    }

    .answer-required {
        border: 1px solid #ccc;
        padding: 5px 10px;
        font-weight: normal;
        margin-top: 10px;
    }

    button {
        border: 1px solid #ccc;
        background-color: #3694f7;
        color: #fff !important;
    }

    #surveyElements {
        background-color: #ebebeb;
        padding: 20px;
    }

    .addQBT {
        margin-top: 10px;
    }
</style>
@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Edit Survey
        <a style="font-size:16px; background-color: #1e9e33; color: #fff;padding: 5px 10px" class="pull-right" href="{{ route('admin.surveys.toggle-publish',$survey->id) }}">{{ $survey->is_active ? 'Unpublish' : 'Publish'}}</a>
        <a target="_blank" style="font-size:16px; margin-right:20px;background-color: #cc7620; color: #fff;padding: 5px 10px" class="pull-right" href="{{ route('admin.surveys.preview',$survey->id) }}">Preview</a>
        <a style="font-size:16px; margin-right:20px; background-color: #9e160a; color: #fff;padding: 5px 10px" class="pull-right" href="{{ route('admin.surveys.delete',$survey->id) }}" onclick="return window.confirm('Are you sure you want to delete this?');">Delete</a>
    </h1>
</section>

<!-- Main content -->
<section class="content">
    <div class="box box-info">
        <div class="box-header">
            <div class="col-md-12">
                @if(Session::has('message'))
                    <div class="alert alert-success">
                        {{ Session::get('message') }}
                    </div>
                @endif
                <!-- /. tools -->
            </div>
        </div>
        <!-- /.box-header -->

        <div class="row">
            <div class="col-md-12">
                <div class="box-body pad">
                    {!! Form::open(['route'=> 'admin.surveys.update','files'=>true,'id'=>'surveyForm']) !!}
                    {!! Form::hidden('id',$survey->id) !!}
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Title</label>
                            <input type="text" name="survey[title]" required class="form-control" value="{{ $survey->title }}">
                        </div>
                    </div>

                    <div class="col-md-12">
                        <div class="form-group">
                            <label>Description</label>
                            <textarea class="editor" name="survey[description]" rows="10" cols="80">{{ $survey->description }}</textarea>
                        </div>
                    </div>

                    <div class="col-md-12">
                        <label>Short Thumbnail ( 320x240 )</label><br>
                        <img src="{{ $survey->thumbnail }}" height="100">
                        <input type="file" class="form-control"  value="" name="thumbnail">
                        <br>
                        <br>
                        <label>Long Thumbnail ( 720x270 )</label><br>
                        <img src="{{ $survey->photo }}" height="100">
                        <br>
                        <br>
                        <input type="file" class="form-control"  value="" name="photo">

                        <hr>

                        <div class="col-md-12">
                            <div class="row">
                                Remove Thumbnails &nbsp;<input type="checkbox" name="remove_thumb">
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <hr>
                        <h3>Questions</h3>
                        <div id="surveyElements">
                            @foreach($survey->questions as $index=>$question)
                                <?php
                                $el = '';
                                $is_float = $question->is_float ? 'checked' : '';

                                if($question->type){

                                    $el = '<div class="form-group clearfix ui-state-default" data-id="'.$question->id.'">';

                                    if($question->type->slug=='text')
                                    {
                                        $el .='<label>Text Field Question </label>';
                                    } else if ($question->type->slug=='textarea')
                                    {
                                        $el .='<label>Textarea Question </label>';
                                    } else if ($question->type->slug=='radio')
                                    {
                                        $el .='<label>Multiple Choices with single answers</label>';
                                    } else if ($question->type->slug=='checkbox')
                                    {
                                        $el .='<label>Multiple Choices with multiple answers</label>';
                                    } else if ($question->type->slug=='date')
                                    {
                                        $el .='<label>Date Question </label>';
                                    }

                                    $el .='<input type="text" class="form-control" name="question['.$question->id.'][question]" style="margin-bottom: 10px;" value="'.$question->question.'" placeholder="Add question here...">';
                                    $el .='<span class="delete-question"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></span><span class="move-question"><span class="glyphicon glyphicon-move" aria-hidden="true"></span></span>';

                                    if ($question->type->slug=='radio'|| $question->type->slug=='checkbox')
                                    {
                                        $el .='<div class="row"><div class="field-group col-md-6"><label>Choices</label>';

                                        $el .= ' [ Display side by side <input name="question['.$question->id.'][is_float]" value="1" type="checkbox" '.$is_float.'> ]';
                                        $el .='<br>';

                                        $choiceCount = 1;
                                        foreach($question->choices as $question->idIn=>$choice){
                                            $el .= '<div class="choice"><input type="text" name="question['.$question->id.'][choices]['.$choiceCount.'][choice]" value="'.$choice->value.'">';

                                            if($choiceCount>1)
                                                $el .= '<span class="glyphicon glyphicon-remove-sign delete-choice" aria-hidden="true"></span>';

                                            $choiceCount++;

                                            $el .= '</div>';
                                        }

                                        $el .='<button type="button" class="addQBT">+ Add a choice</button><br>';
                                    }
                                    else if ($question->type->slug=='rate')
                                    {
                                        $el .='<div class="row"><div class="field-group col-md-6"><label>Items</label>';

                                        $el .='<br>';

                                        $choiceCount = 1;
                                        foreach($question->choices as $question->idIn=>$choice){
                                            $el .= '<div class="choice"><input type="text" name="question['.$question->id.'][choices]['.$choiceCount.'][choice]" value="'.$choice->value.'">';
                                            $el .= '<select class="rateSelect" name="question['.$question->id.'][choices]['.$choiceCount.'][rate]">';
                                            $el .= '<option value="5" '.( $choice->ratability == 5 ? 'selected' : '' ).'>1 to 5</option>';
                                            $el .= '<option value="10" '.( $choice->ratability == 10 ? 'selected' : '' ).'>1 to 10</option>';
                                            $el .= '</select>';

                                            if($choiceCount>1)
                                                $el .= '<span class="glyphicon glyphicon-remove-sign delete-choice" aria-hidden="true"></span>';

                                            $choiceCount++;

                                            $el .= '</div>';
                                        }

                                        $el .='<button type="button" class="addRBT">+ Add a item</button><br>';
                                    }
                                    else
                                    {
                                        $el .='<div class="row"><div class="field-group col-md-6"><br><br>';
                                    }

                                    $el .='<input type="hidden" name="question['.$question->id.'][type]" value="'.$question->type->slug.'">';

                                    $el .='<br></div><div class="col-md-6"><label class="pull-right answer-required">Answer required <input name="question['.$question->id.'][is_required]" value="1" type="checkbox" '.( $question->is_required ? 'checked' : '').'></label></div>';

                                    $el .='</div>';

                                    $el .='<input type="text" class="count" readonly="readonly" name="question['.$question->id.'][order]" value="'.$question->order.'">';

                                    $el .='</div>';

                                    echo $el;
                                }
                                ?>
                            @endforeach
                        </div>
                        <hr>
                        <label>Type</label>
                        {!! Form::select('survey[type]',$data['types'],$survey->survey_question_type_id,['class'=>'selectpicker form-control','id'=>'typeSelector']) !!}
                        <br>
                        <button id="addQuestionBt" type="button" class="pull-left">Add a question</button>
                        <button id="submitForm" class="pull-right">Save Survey</button>
                    </div>

                    {!! Form::close() !!}

                </div>
            </div>
        </div>
    </div>
</section>
<!-- /.content -->

@endsection

@section('custom-js')
    <script src="{{ asset('public/js/survey.js') }}"></script>
    <script>
        addQBTClickEvent();
        addRBTClickEvent();
        addDeleteQuestionClickEvent();
        updateSortable();
    </script>
@endsection